@startjson
{
  "Person": {
    "_id": "ObjectId",
    "Name": "String",
    "Email": "String",
    "DOB": "String",
    "Addresses": [
      {
      "Type": "String",
      "Street": "String",
      "City": "String",
      "Country": "String",
      "Zip Code": "String"
      }
    ],
    "Neighbours": [
      {
        "Neighbour Name": "String",
        "Neighbour Email": "String"
      }
    ],
    "Favourites": [
      {
        "Type": "String",
        "Value": "String"
      }
    ]
  }
}
@endjson