@startuml 1NF

hide circle

entity "1NF" {
  * id : INTEGER NOT NULL <<PK>>
  --
  * name : VARCHAR(255) NOT NULL
  * email : VARCHAR(255) NOT NULL
  * dob : DATE NOT NULL
  * street : VARCHAR(255) NOT NULL
  * city : VARCHAR(255) NOT NULL
  * country : VARCHAR(255) NOT NULL
  * zipcode : VARCHAR(255) NOT NULL
  * favourite_books : VARCHAR(255) NOT NULL
  * favourite_drink : VARCHAR(255) NOT NULL
  * favourite_activity : VARCHAR(255) NOT NULL
  * neighbour_name : VARCHAR(255) NOT NULL
  * neighbour_email : VARCHAR(255) NOT NULL
}

@enduml